import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useNotifications } from "@/lib/hooks/useNotifications";
import NotificationToast from "@/components/NotificationToast";
import { useAuth } from "@/lib/hooks/useAuth"; // Assume you have an auth hook

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = useAuth(); // Get the logged-in user ID
  const { newAlert, clearAlert } = useNotifications(user?.id);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* The Toast will appear globally on any page if a new alert comes in */}
        <NotificationToast alert={newAlert} onClose={clearAlert} />

        {children}
      </body>
    </html>
  );
}
